services:
  yacl-runner:
    image: yacl-runner
    container_name: yacl-runner
    user: "0:0"
    restart: unless-stopped
    environment:
      GITHUB_URL: ${GITHUB_URL:-https://github.com/yale-acl/yacl-website}
      RUNNER_TOKEN: ${RUNNER_TOKEN}
      SSH_SOURCE_DIR: /runner-ssh
    volumes:
      - yacl-runner-work:/home/runner/_work
      - ${SSH_HOST_DIR:-${HOME}/yacl-runner-ssh}:/runner-ssh:ro

volumes:
  yacl-runner-work:
